---
title: "Denver Crime"
author: "Matt Majestic"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(tidyr)
library(lubridate)
library(DT)
library(plotly)
library(stringr)
mj_crime <- read.csv("C:/Users/mmajesti/Desktop/denver_crimes/mj_crime.csv",stringsAsFactors = FALSE)
neigh_piv <- mj_crime %>% group_by(Year,NEIGHBORHOOD_ID) %>% summarise(Count = n()) %>% spread(Year,Count,fill = 0) 
neigh_piv$total <- neigh_piv %>% select(starts_with("201")) %>% rowSums 
neigh_piv <- neigh_piv %>% arrange(desc(total))
offense_chart <- mj_crime %>% select(Year,OFFENSE_TYPE_ID) %>% mutate(Offense = stringr::word(OFFENSE_TYPE_ID,1))  %>% group_by(Year,Offense) %>% summarise(Count = n()) %>% arrange(desc(Count))

```

## Marijuana related crimes in Denver

From the **Denver Gov Open Data Catalog**


```{r cars,warning=FALSE}
datatable(neigh_piv)
## Sorted by Total and Grouped by Neighborhood ##
```

## Types of crime over the last 5 years

Plot by crime type

```{r pressure,warning=FALSE}
plot_ly(offense_chart,x=~Year,y=~Count,size=~Count,color =~Offense,type = "scatter")
## This could use more cleaning of names ##
```

## Total Over 5 Years

Pie Chart of the percentage of marijuana related crimes

```{r pie,warning=FALSE}
plot_ly(offense_chart, labels = ~Offense, values = ~Count, type = 'pie')
```